pipeline {
    agent any

    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout SCM 성공'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('eureka-service') {
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                    sh "${DOCKER} build -t jongmin627/eureka-service ."
                }
                echo 'Build Docker Image 성공'
            }
        }

        stage('Remove Previous container') {
            steps {
                script {
                    try {
                        sh "${DOCKER} stop eureka-service"
                        sh "${DOCKER} rm eureka-service"
                    } catch (e) {
                        echo 'fail to stop and remove previous container (없는 경우 무시)'
                    }
                }
            }
        }

        stage('Run New container') {
            steps {
                sh "${DOCKER} run --name eureka-service -d -p 8761:8761 jongmin627/eureka-service"
                echo 'Run New Eureka-Service 성공'
            }
        }
    }
}