pipeline {
    agent any

    environment {
        DOCKER = 'docker' // 필요시 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Repository cloned'
            }
        }

        stage('Build eureka-service') {
            steps {
                sh './gradlew :eureka-service:bootJar -x test'
                echo 'Gradle build finished'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t jongmin627/eureka-service -f eureka-service/Dockerfile .'
                echo 'Docker image built'
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    try {
                        sh 'docker stop eureka-service || true'
                        sh 'docker rm eureka-service || true'
                    } catch (e) {
                        echo 'No running container to stop'
                    }

                    sh 'docker run --name eureka-service -d -p 8761:8761 jongmin627/eureka-service'
                    echo 'Container started'
                }
            }
        }
    }
}