pipeline {
    agent any

    environment {
        DOCKER = 'docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo '✅ SCM 클론 성공'
            }
        }

        stage('Build config-service image') {
            steps {
                dir('config-service') {
                    sh '''
                        chmod +x ./gradlew
                        ./gradlew clean build
                        ${DOCKER} build -t jongmin627/config-service .
                    '''
                }
                echo '✅ config-service Docker Image 빌드 성공'
            }
        }

        stage('Create Docker Network if not exists') {
                    steps {
                        script {
                            sh """
                                if [ -z "\$(docker network ls --filter name=^msa-net\$ --format='{{ .Name }}')" ]; then
                                  echo "Creating msa-net network..."
                                  docker network create msa-net
                                else
                                  echo "Docker network msa-net already exists"
                                fi
                            """
                        }
                    }
                }


        stage('Prepare .env and Run config-service') {
            steps {
                withCredentials([
                    string(credentialsId: 'git-uri', variable: 'GIT_URI'),
                    string(credentialsId: 'git-paths', variable: 'GIT_SEARCH_PATHS'),
                    string(credentialsId: 'git-label', variable: 'GIT_DEFAULT_LABEL'),
                    string(credentialsId: 'ssh-private-key', variable: 'SSH_PRIVATE_KEY'),
                    string(credentialsId: 'ssh-host-key', variable: 'SSH_HOST_KEY'),
                    string(credentialsId: 'ssh-algorithm', variable: 'SSH_HOST_KEY_ALGORITHM'),
                    string(credentialsId: 'ssh-passphrase', variable: 'SSH_PASSPHRASE')
                ]) {
                    sh '''

                        echo "GIT_URI=$GIT_URI" > ${WORKSPACE}/.env
                        echo "GIT_SEARCH_PATHS=$GIT_SEARCH_PATHS" >> ${WORKSPACE}/.env
                        echo "GIT_DEFAULT_LABEL=$GIT_DEFAULT_LABEL" >> ${WORKSPACE}/.env
                        echo "GIT_IGNORE_LOCAL_SSH_SETTINGS=true" >> ${WORKSPACE}/.env
                        echo "SSH_HOST_KEY=$SSH_HOST_KEY" >> ${WORKSPACE}/.env
                        echo "SSH_HOST_KEY_ALGORITHM=$SSH_HOST_KEY_ALGORITHM" >> ${WORKSPACE}/.env
                        echo "SSH_PASSPHRASE=$SSH_PASSPHRASE" >> ${WORKSPACE}/.env
                        printf "%b" "$SSH_PRIVATE_KEY" > ${WORKSPACE}/id_rsa
                        chmod 600 ${WORKSPACE}/id_rsa


                    '''

                    sh '''
                        ${DOCKER} stop config-service || true
                        ${DOCKER} rm config-service || true

                        ${DOCKER} run -e SSH_PRIVATE_KEY="$(cat ${WORKSPACE}/id_rsa)" \
                        --name config-service -d -p 8888:8888 \
                        --network msa-net \
                        --env-file ${WORKSPACE}/.env \
                        jongmin627/config-service
                    '''
                    echo '🚀 config-service 실행 완료'
                }
            }
        }
    }
}