server:
  port: 8000

spring:
  application:
    name: gateway-servivce
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
