server:
  port: 9030

spring:
  application:
    name: reservation-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /reservation-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html