server:
  port: 8761

spring:
  application:
    name: eureka-service
  cloud:
    config:
      uri: http://config-server:8888  # Config Server와 연결
      fail-fast: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true