server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    import: optional:file:.env[.properties]

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          search-paths: ${GIT_SEARCH_PATHS}
          default-label: ${GIT_DEFAULT_LABEL}
          ignore-local-ssh-settings: ${GIT_IGNORE_LOCAL_SSH_SETTINGS}
          host-key: ${SSH_HOST_KEY}
          host-key-algorithm: ${SSH_HOST_KEY_ALGORITHM}
          private-key: /run/secrets/id_rsa
          passphrase: ${SSH_PASSPHRASE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true