name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eureka-service -f ./eureka-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eureka-service
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service -f ./gateway-service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service

#          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service -f ./user-service/Dockerfile .
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service
#
#          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/caregiver-service -f ./caregiver-service/Dockerfile .
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/caregiver-service

